absubmit:
  - 'absubmit'
acousticbrainz:
  - 'acousticbrainz'
advancedrewrite:
  - 'advancedrewrite'
albumtypes:
  - 'albumtypes plugin'
  - 'albumtypes:'
aura:
  - 'aura'
autobpm:
  - 'autobpm'
badfiles:
  - 'badfiles'
bareasc:
  - 'bareasc'
beatport:
  - 'beatport'
bpd:
  - 'bpd'
bpsync:
  - 'bpsync'
bucket:
  - 'bucket'
chroma:
  - 'chroma'
convert:
  - 'convert plugin'
  - 'convert:'
deezer:
  - 'deezer'
discogs:
  - 'discogs'
duplicates:
  - 'duplicates plugin'
  - 'duplicates:'
edit:
  - 'edit plugin'
  - 'edit:'
embedart:
  - 'embedart'
embyupdate:
  - 'embyupdate'
export:
  - 'export plugin'
  - 'export:'
fetchart:
  - 'fetchart'
filefilter:
  - 'filefilter'
fish:
  - 'fish'
freedesktop:
  - 'freedesktop'
fromfilename:
  - 'fromfilename'
ftintitle:
  - 'ftintitle'
fuzzy:
  - 'fuzzy plugin'
  - 'fuzzy:'
hook:
  - 'hook plugin'
  - 'hook:'
ihate:
  - 'ihate'
importadded:
  - 'importadded'
importfeeds:
  - 'importfeeds'
importsource:
  - 'importsource'
info:
  - 'info plugin'
  - 'info:'
inline:
  - 'inline plugin'
  - 'inline:'
ipfs:
  - 'ipfs'
keyfinder:
  - 'keyfinder'
kodiupdate:
  - 'kodiupdate'
lastgenre:
  - 'lastgenre'
lastimport:
  - 'lastimport'
limit:
  - 'limit plugin'
  - 'limit:'
listenbrainz:
  - 'listenbrainz'
loadext:
  - 'loadext'
lyrics:
  - 'lyrics'
mbcollection:
  - 'mbcollection'
mbpseudo:
  - 'mbpseudo'
mbsubmit:
  - 'mbsubmit'
mbsync:
  - 'mbsync'
metasync:
  - 'metasync'
missing:
  - 'missing plugin'
  - 'missing:'
mpdstats:
  - 'mpdstats'
mpdupdate:
  - 'mpdupdate'
musicbrainz:
  - 'musicbrainz'
parentwork:
  - 'parentwork'
permissions:
  - 'permissions plugin'
  - 'permissions:'
play:
  - 'play plugin'
  - 'play:'
playlist:
  - '\bplaylist plugin'
  - '\bplaylist:'
plexupdate:
  - 'plexupdate'
random:
  - 'random plugin'
  - 'random:'
replace:
  - 'replace plugin'
  - 'replace:'
replaygain:
  - 'replaygain'
rewrite:
  - '\brewrite plugin'
  - '\brewrite:'
scrub:
  - 'scrub'
smartplaylist:
  - 'smartplaylist'
sonosupdate:
  - 'sonosupdate'
spotify:
  - 'spotify'
subsonicplaylist:
  - 'subsonicplaylist'
subsonicupdate:
  - 'subsonicupdate'
substitute:
  - 'substitute'
thumbnails:
  - 'thumbnails'
titlecase:
  - 'titlecase'
types:
  - '\btypes plugin'
  - '\btypes:'
unimported:
  - 'unimported'
web:
  - 'web plugin'
  - 'web:'
zero:
  - 'zero plugin'
  - 'zero:'
