# Configuration for probot-stale - https://github.com/probot/stale

daysUntilClose: 7
staleLabel: stale

issues:
  daysUntilStale: 60
  onlyLabels:
    - needinfo
  markComment: >
    This issue has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank you
    for your contributions.
