comment:
  layout: "header, diff, files"
  require_changes: true

# Sets non-blocking status checks
# https://docs.codecov.com/docs/commit-status#informational
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
    changes: false
