# This file is part of beets.
# Copyright 2024, Arav K.
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.

"""
Tests for the `fish` plugin.
"""

import optparse
from pathlib import Path

import pytest

from beets.library import Library
from beetsplug.fish import FishPlugin


@pytest.fixture
def fish_plugin() -> FishPlugin:
    """
    A fixture returning an instance of the `fish` plugin.
    """

    return FishPlugin()


class TestFish:
    """
    Tests for the `fish` plugin.
    """

    def test_fish_simple(
        self,
        tmp_path: Path,
        resource_dir: Path,
        library: Library,
        fish_plugin: FishPlugin,
    ):
        """
        Test that the script generated by default matches a preset file.
        """

        output = tmp_path / "script.fish"
        expected = resource_dir / "fish" / "simple.fish"

        # Generate a script with default behaviour.
        opts = optparse.Values()
        opts.output = str(output)
        opts.noFields = False
        opts.extravalues = []
        fish_plugin.run(library, opts, [])

        # Match the generated script to a preset version.
        assert output.read_text() == expected.read_text()
