name: formatting_check
run-name: Check code formatting
on: [push, pull_request]
jobs:
  formatting_check:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: actions/checkout@v3

      - name: Run formatting check
        uses: paolorechia/pox@v1.0.1
        with:
          tox_env: "format_check"
